noun 1 = input(“Enter a noun”)
place = input(“Enter a place”)
action =  input(“Enter an action”)
pronoun = input(“Enter a pronoun”)
noun 2 = input(“Enter a noun”)
noun 3 = input(“Enter a noun”) 
adjective 1 = input(“Enter an adjective”)
adjective 2 = input(“Enter an adjective”)
emotion = input(“Enter an emotion”)

print(“Once upon a time there lived a ” + noun 1)
print(noun 1 + “ needed to” + action “ at ” + place)
print(noun 1 + “ started on ” + pronoun “  journey”)
print(noun 1 + “ brought some ” + noun 2 “along”)
print(“Then appeared a ” + noun 3)
print(“It was ” + adjective 1 “ and ” + adjective 2)
print(noun 1 + “ was ” + emotion)
print(pronoun + "ran and ran and never stopped")
