#loops the whole game
keepPlaying = True
while (keepPlaying):
    print("Welcome to create your own MadLib Story!")
    break

#user enters words
noun1 = input('Enter a noun: ')
noun2 = input('Enter a noun: ')
noun3 = input('Enter a noun: ')
noun4 = input('Enter a noun: ')
noun5 = input('Enter a noun: ')
place = input('Enter a place: ')
pronoun = input("Enter a pronoun: ")
action =  input('Enter an action: ')
adjective1 = input('Enter an adjective: ')
adjective2 = input('Enter an adjective: ')
emotion = input('Enter an emotion: ')
adjective3 = input("Enter an adjective: ")
adjective4 = input("Enter an adjective: ")
adjective5 = input("Enter an adjective: ")
adjective6 = input("Enter an adjective: ")

#entered words are put into  story
print('Once upon a time there lived a' + ' ' + noun1)
print(noun1 + ' ' + 'needed to' + ' ' + action + ' ' + 'at' + ' ' + place)
print(noun1 + ' ' + 'started on their journey')
print(noun1 + ' ' + 'brought some' + ' ' + noun2 + ' ' + 'along')
print('Then appeared a' + ' ' + noun3)
print('It was' + ' ' + adjective1 + ' ' + 'and' + ' ' + adjective2)
print(noun1 + ' ' + 'was' + ' ' + emotion)
print(pronoun + ' ' + "ran and ran and never stopped")
print(pronoun + ' ' + "ran until they fell in")
print(pronoun + ' ' + "fell into the void")
print("the void became a dark hole in which" + ' ' + pronoun + ' ' + "landed in a" + ' ' + adjective3 + ' ' + "place")
print("This place was unlike their home")
print("A" + ' ' + adjective4 + ' ' + "that all worries faded away")
print(noun1 + ' ' + "didn't know what to do, or how to get back")
print(pronoun + ' ' + "needed to find a way to get back")
print("And so" + ' ' + noun1 + ' ' + 'started to walk and walk')
print("Along the way" + ' ' + noun1 + ' ' + "met a" + ' ' + noun4)
print("It was" + ' ' + adjective5 + ' ' "and" + adjective6)
print("But" + ' ' + noun1 +  ' ' + "felt bad, and so" + ' ' + pronoun + ' ' + noun4 + ' ' + "to come along")
print("The" + ' ' + noun4 + ' ' "agreed and started along with" + ' ' + noun1)
print("they heard a noise and came to a stop, I wonder what it is said" + ' ' + noun1)
print("It was a ferocious" + ' ' + noun5)
print("But of course" + ' ' + noun1 + ' ' + "asked if it wanter to come along to their journey")
print("the" + ' ' + noun5 + ' ' + "agreed to come with")
print("and so their journey to find a way out continued")
print("It was not til they reached a place of music")
print("This land of mucic was peaceful and colorful")
print("And at the end of the road, there was a little cottage")
print("The cottage looked very familiar to" + ' ' + noun1)
print("It was" + ' ' + noun1 + "'s" + place)      
print("Final destination reached")

print("The End")
