noun1 = input(“Enter a noun”)
place = input(“Enter a place”)
action =  input(“Enter an action”)
pronoun = input(“Enter a pronoun”)
noun2 = input(“Enter a noun”)
noun3 = input(“Enter a noun”) 
adjective1 = input(“Enter an adjective”)
adjective2 = input(“Enter an adjective”)
emotion = input(“Enter an emotion”)
adjective3 = input("Enter an adjective")

print(“Once upon a time there lived a” + noun1)
print(noun1 + “ needed to” + action “at” + place)
print(noun1 + “started on” + pronoun “journey”)
print(noun1 + “brought some” + noun2 “along”)
print(“Then appeared a” + noun3)
print(“It was” + adjective1 “and” + adjective2)
print(noun1 + “was” + emotion)
print(pronoun + "ran and ran and never stopped")
print(pronoun + "ran until" + pronoun + "fell in")
print(pronoun + "fell into the void")
print("the void become a dark hole in which" + pronoun + "landed in a" + adjective3 + "place")
print ()
